//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first_site_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id_Doc { get; set; }
        public string Type_Document { get; set; }
        public int Dossier_Id_Dossier { get; set; }
        public byte[] Fichier { get; set; }
        public Nullable<byte> Est_Valide { get; set; }
    
        public virtual Dossier Dossier { get; set; }
    }
}
