//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first_site_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportAsso_BDDEntities : DbContext
    {
        public SportAsso_BDDEntities()
            : base("name=SportAsso_BDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Creneau> Creneau { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Dossier> Dossier { get; set; }
        public virtual DbSet<Lieu> Lieu { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
